language: node_js
os:
  - linux
  - osx
node_js:
  - 8.9.0
cache: # 缓存 node_js 依赖，提升第二次构建的效率
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_b0ed3251d3fd_key -iv $encrypted_b0ed3251d3fd_iv
    -in super_secret.txt.enc -out super_secret.txt -d
after_success:
  - ssh root@120.79.161.225 "cd /home/MyBlog;git pull;npm install;npm run build;"
