language: node_js
node_js:
  - 8.9.0
cache:
  directories:
    - node_modules
before_install:
  - chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh root@120.79.161.225 "cd /home/MyBlog;git pull;npm install;npm run build;"
addons:
  ssh_known_hosts: 120.79.161.225
