language: node_js
os:
  - linux
  - osx
node_js:
  - 8.9.0
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_b0ed3251d3fd_key -iv $encrypted_b0ed3251d3fd_iv
    -in github.pub.enc -out ~\/.ssh/github.pub -d
after_success:
  - ssh root@120.79.161.225 "cd /home/MyBlog;git pull;npm install;npm run build;"
addons:
  ssh_known_hosts: 120.79.161.225
