language: node_js
node_js:
  - 8.9.0
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_2a36be4ef7a3_key -iv $encrypted_2a36be4ef7a3_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh root@120.79.161.225 'cd /home/MyBlog && git pull && npm install && npm run build'
  - ls /home
addons:
  ssh_known_hosts: 120.79.161.225
