language: node_js
node_js:
  - 8.9.0
cache:
  directories:
    - node_modules
before_install:
  - ls ~/.ssh
  - openssl aes-256-cbc -K $encrypted_b0ed3251d3fd_key -iv $encrypted_b0ed3251d3fd_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
after_success:
  - ssh root@120.79.161.225 "cd /home/MyBlog;git pull;npm install;npm run build;"
addons:
  ssh_known_hosts: 120.79.161.225
